module AppMarketScraper
  HTTP = 'https://'

  GOOGLE_PLAY_BASE_URL = HTTP + 'play.google.com'
  GOOGLE_PLAY_STORE_URL = GOOGLE_PLAY_BASE_URL + '/store'
  GOOGLE_PLAY_SEARCH_URL = GOOGLE_PLAY_STORE_URL + '/search'
  GOOGLE_PLAY_DETAIL_URL = GOOGLE_PLAY_STORE_URL + '/apps/details'
  GOOGLE_PLAY_CATEGORY_APPS_URL = GOOGLE_PLAY_STORE_URL + '/apps'
  GOOGLE_PLAY_CATEGORY_URL = GOOGLE_PLAY_STORE_URL + '/apps/category'

  APPLE_APP_STORE_BASE_URL = 'https"//changeurl please'
end